
stages:
  - test
  - fetchConfig
  - build

image: node:20-bookworm-slim



# The workflow property decides whether this pipeline should run at all
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        CONFIG_BRANCH: int
    - if: $CI_COMMIT_REF_NAME == "main"
      variables:
        CONFIG_BRANCH: qas
    - if: $CI_COMMIT_TAG
      variables:
        CONFIG_BRANCH: prd
    # In all other cases, do not run


test:
  stage: test
  script:
    - npm ci
    - npm run build
    - npm run test

fetchConfig:
  image:
    name:  alpine/git:2.40.1
    entrypoint: [""]
  
  script:
    - echo "Fetching configuration from config branch ${CONFIG_BRANCH}"
    - git clone --depth 1 -b ${CONFIG_BRANCH} https://gitlab-ci-token:${CI_JOB_TOKEN}@git.triply.cc/customers/meemoo/grasp-config.git
    - rm -r ./grasp-config/.git ./grasp-config/Dockerfile ./grasp-config/README.md ./grasp-config/.gitlab-ci.yml
  artifacts:
    paths:
    - grasp-config
    expire_in: 1 week


build-org:
  stage: build
  image: docker:20.10.18-cli
  variables:
    GRASP_CONFIG: org
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} registry.triply.cc
    - docker build --build-arg "ENDPOINT=${ENDPOINT}" --build-arg "GRASP_CONFIG=${GRASP_CONFIG}" -t registry.triply.cc/customers/meemoo/grasp:${GRASP_CONFIG}-${CONFIG_BRANCH} .
    - docker push registry.triply.cc/customers/meemoo/grasp:${GRASP_CONFIG}-${CONFIG_BRANCH}

build-objects:
  stage: build
  image: docker:20.10.18-cli
  variables:
    GRASP_CONFIG: objects
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} registry.triply.cc
    - docker build --build-arg "ENDPOINT=${ENDPOINT}" --build-arg "GRASP_CONFIG=${GRASP_CONFIG}" -t registry.triply.cc/customers/meemoo/grasp:${GRASP_CONFIG}-${CONFIG_BRANCH} .
    - docker push registry.triply.cc/customers/meemoo/grasp:${GRASP_CONFIG}-${CONFIG_BRANCH}

